#!/bin/sh
echo "$(date) Startup" > /tmp/f2b

ps >> /tmp/f2b
sleep 10
echo "$(date) Startup" >> /tmp/f2b
ps >> /tmp/f2b

logger "starting fail2ban"

export PYTHONPATH=/usr/lib/python2.7/site-packages/lib
fail2ban-client start  >> /tmp/f2b 2>&1

echo "$(date) End" >> /tmp/f2b
exit 0
